import pg from "pg";
import { env } from "./env.mjs";
const c = new pg.Client({ connectionString: env.DATABASE_URL, ssl: { rejectUnauthorized: false } });
await c.connect();
const q = async (label, sql) => { try { const r = await c.query(sql); console.log("\n== " + label); console.table(r.rows.slice(0,16)); } catch(e){ console.log("\n== " + label + "  ERR: " + e.message); } };
await q("varsity tables present", `select table_name from information_schema.tables where table_schema='public' and table_name like 'varsity%' order by 1`);
await q("plan_sessions columns", `select column_name, data_type from information_schema.columns where table_schema='public' and table_name='varsity_plan_sessions' order by ordinal_position`);
await q("recent plan sessions", `select day_key, category, intensity, description from public.varsity_plan_sessions order by day_key desc limit 8`);
await q("varsity members", `select * from public.varsity_members limit 8`);
await q("owner-ish users", `select id, email from auth.users where email ilike '%martinhouska%' or email ilike '%brown%'`);
await c.end();
